availableSecrets:
  secretManager:
    - versionName: projects/${_PROJECT_ID}/secrets/google-api-key/versions/latest
      env: 'GOOGLE_API_KEY'

steps:
# Verify that secrets are loaded
- id: "Verify Secrets"
  name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args:
    - "-c"
    - |
      echo "Verifying secrets are available:"
      echo "GOOGLE_API_KEY length: ${#GOOGLE_API_KEY}"
  secretEnv: ['GOOGLE_API_KEY']

# Clone the repository from GitHub
- id: 'Cloning Repository...'
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/${_GITHUB_REPO}.git', '--branch=${_GITHUB_BRANCH}', '--depth=1']

# Run unit tests using pytest with coverage enforcement
- id: 'Running Unit Tests...'
  name: 'python:3.12'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -e
      cd ${_REPO_NAME}
      pip install -r requirements.txt
      pytest tests/ --junitxml=test-results.xml --cov=app --cov-report=term-missing --cov-fail-under=40
      ls -l
  waitFor: ['Cloning Repository...']

# Build the container image
- id: 'Building Image...'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/api-demo/${_IMAGE}:latest', '.']
  waitFor: ['Running Unit Tests...']

# Push the container image to Container Registry
- id: 'Pushing Image...'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/api-demo/${_IMAGE}:latest']
  waitFor: ['Building Image...']

- id: "Deploying Image...."
  name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args: [
    '-c',
    'gcloud run deploy "${_SERVICE_NAME}" 
    --image "us-central1-docker.pkg.dev/${_PROJECT_ID}/api-demo/${_IMAGE}:latest" 
    --region "${_REGION}" 
    --allow-unauthenticated
    --service-account "${_SERVICE_ACC}"
    --set-env-vars GOOGLE_API_KEY=$$GOOGLE_API_KEY
    '
  ]
  secretEnv: ['GOOGLE_API_KEY']
  waitFor: ['Pushing Image...']

# Upload test results
- id: 'Upload Results to Cloud Storage'
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '${_REPO_NAME}/test-results.xml', 'gs://cicd-reports-${_PROJECT_ID}/test-results/']
  waitFor: ['Deploying Image....']

images:
- us-central1-docker.pkg.dev/${_PROJECT_ID}/api-demo/${_IMAGE}:latest

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
